//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkorAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartidosCartilla
    {
        public int id { get; set; }
        public int idPartido { get; set; }
        public int idCartilla { get; set; }
        public string descripcion { get; set; }
        public string grupo { get; set; }
    
        public virtual Cartillas Cartillas { get; set; }
        public virtual Partidos Partidos { get; set; }
    }
}
