//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkorAdmin.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class skorEntities : DbContext
    {
        public skorEntities()
            : base("name=skorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cartillas> Cartillas { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Partidos> Partidos { get; set; }
        public virtual DbSet<PartidosCartilla> PartidosCartilla { get; set; }
    
        public virtual int SP_PROC_CalificaPorPartido(Nullable<int> idPartido)
        {
            var idPartidoParameter = idPartido.HasValue ?
                new ObjectParameter("idPartido", idPartido) :
                new ObjectParameter("idPartido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PROC_CalificaPorPartido", idPartidoParameter);
        }
    
        public virtual int SP_PROC_RecalculaCartillas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PROC_RecalculaCartillas");
        }
    
        public virtual int SP_CerrarCartillas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CerrarCartillas");
        }
    }
}
