//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ApuestasEntities : DbContext
    {
        public ApuestasEntities()
            : base("name=ApuestasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<a2022_Apuestas_JuegosPublicados_Lista_Result> a2022_Apuestas_JuegosPublicados_Lista()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<a2022_Apuestas_JuegosPublicados_Lista_Result>("a2022_Apuestas_JuegosPublicados_Lista");
        }
    }
}
