//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvancesFase
    {
        public int id { get; set; }
        public int idPartido { get; set; }
        public Nullable<int> idGrupo { get; set; }
        public Nullable<int> posicion { get; set; }
        public Nullable<int> numeroEquipo { get; set; }
    
        public virtual Partidos Partidos { get; set; }
    }
}
