//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bandos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bandos()
        {
            this.UsuariosBandos = new HashSet<UsuariosBandos>();
        }
    
        public int id { get; set; }
        public int idTipo { get; set; }
        public int idAdmin { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public Nullable<bool> esAbierto { get; set; }
        public Nullable<int> puntos { get; set; }
        public Nullable<int> miembros { get; set; }
        public Nullable<int> posicion { get; set; }
        public string descripcion { get; set; }
        public string condiciones { get; set; }
        public string premios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosBandos> UsuariosBandos { get; set; }
        public virtual USR_usuarios USR_usuarios { get; set; }
    }
}
