//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartillas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cartillas()
        {
            this.CartillasUsuario = new HashSet<CartillasUsuario>();
            this.PartidosCartilla = new HashSet<PartidosCartilla>();
        }
    
        public int id { get; set; }
        public Nullable<int> idEmpresa { get; set; }
        public Nullable<int> idAdministrador { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public string descripcion { get; set; }
        public string premios { get; set; }
        public string condiciones { get; set; }
        public Nullable<bool> estaCerrada { get; set; }
        public string urlBanner { get; set; }
        public Nullable<bool> estaTerminada { get; set; }
        public Nullable<bool> estaActiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartillasUsuario> CartillasUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartidosCartilla> PartidosCartilla { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual USR_usuarios USR_usuarios { get; set; }
    }
}
