//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartillasUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CartillasUsuario()
        {
            this.Pronosticos = new HashSet<Pronosticos>();
        }
    
        public int id { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idCartilla { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<bool> estaSellada { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaSellada { get; set; }
        public Nullable<int> puntos { get; set; }
        public Nullable<int> posicionCierre { get; set; }
        public Nullable<int> posicionResultado { get; set; }
        public Nullable<int> posicionFinal { get; set; }
    
        public virtual Cartillas Cartillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pronosticos> Pronosticos { get; set; }
        public virtual USR_usuarios USR_usuarios { get; set; }
    }
}
