//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIS_Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MIS_Personas()
        {
            this.USR_usuarios = new HashSet<USR_usuarios>();
        }
    
        public int id { get; set; }
        public Nullable<int> idNacionalidad { get; set; }
        public Nullable<int> idEstadoCivil { get; set; }
        public string nombre1 { get; set; }
        public string nombre2 { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string cedula { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<bool> genero { get; set; }
        public string celular { get; set; }
        public Nullable<int> operadora { get; set; }
        public string saludo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USR_usuarios> USR_usuarios { get; set; }
    }
}
