//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partidos()
        {
            this.AvancesFase = new HashSet<AvancesFase>();
            this.PartidosCartilla = new HashSet<PartidosCartilla>();
            this.Pronosticos = new HashSet<Pronosticos>();
        }
    
        public int id { get; set; }
        public Nullable<int> idLiga { get; set; }
        public Nullable<int> idGrupo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> idEquipo1 { get; set; }
        public Nullable<int> idEquipo2 { get; set; }
        public Nullable<int> score1 { get; set; }
        public Nullable<int> score2 { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string descripcion { get; set; }
        public string fase { get; set; }
        public Nullable<bool> esClasificacion { get; set; }
        public Nullable<int> idEquipoClasifico { get; set; }
        public string ubicacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AvancesFase> AvancesFase { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual Equipos Equipos1 { get; set; }
        public virtual Grupos Grupos { get; set; }
        public virtual Ligas Ligas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartidosCartilla> PartidosCartilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pronosticos> Pronosticos { get; set; }
    }
}
