//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartidosCartilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartidosCartilla()
        {
            this.Pronosticos = new HashSet<Pronosticos>();
        }
    
        public int id { get; set; }
        public int idPartido { get; set; }
        public int idCartilla { get; set; }
        public string descripcion { get; set; }
        public string grupo { get; set; }
    
        public virtual Cartillas Cartillas { get; set; }
        public virtual Partidos Partidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pronosticos> Pronosticos { get; set; }
    }
}
