//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pronosticos
    {
        public int id { get; set; }
        public int idUsuario { get; set; }
        public int idPartidoCartilla { get; set; }
        public Nullable<int> idCartillaUsuario { get; set; }
        public Nullable<int> idPartido { get; set; }
        public Nullable<int> idEquipo1 { get; set; }
        public Nullable<int> idEquipo2 { get; set; }
        public Nullable<int> scoreP1 { get; set; }
        public Nullable<int> scoreP2 { get; set; }
        public Nullable<int> puntos { get; set; }
        public Nullable<int> idEquipoClasifica { get; set; }
    
        public virtual CartillasUsuario CartillasUsuario { get; set; }
        public virtual Equipos Equipos { get; set; }
        public virtual Equipos Equipos1 { get; set; }
        public virtual Partidos Partidos { get; set; }
        public virtual PartidosCartilla PartidosCartilla { get; set; }
        public virtual USR_usuarios USR_usuarios { get; set; }
    }
}
