//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class skorEntities : DbContext
    {
        public skorEntities()
            : base("name=skorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvancesFase> AvancesFase { get; set; }
        public virtual DbSet<Cartillas> Cartillas { get; set; }
        public virtual DbSet<CartillasUsuario> CartillasUsuario { get; set; }
        public virtual DbSet<Empresas> Empresas { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Grupos> Grupos { get; set; }
        public virtual DbSet<Ligas> Ligas { get; set; }
        public virtual DbSet<MIS_Personas> MIS_Personas { get; set; }
        public virtual DbSet<Partidos> Partidos { get; set; }
        public virtual DbSet<PartidosCartilla> PartidosCartilla { get; set; }
        public virtual DbSet<Pronosticos> Pronosticos { get; set; }
        public virtual DbSet<USR_usuarios> USR_usuarios { get; set; }
        public virtual DbSet<Bandos> Bandos { get; set; }
        public virtual DbSet<UsuariosBandos> UsuariosBandos { get; set; }
        public virtual DbSet<Rankings> Rankings { get; set; }
    
        public virtual ObjectResult<SP_PronosticosCartillaUsuario_Result> SP_PronosticosCartillaUsuario(Nullable<int> idCartillaUsuario)
        {
            var idCartillaUsuarioParameter = idCartillaUsuario.HasValue ?
                new ObjectParameter("idCartillaUsuario", idCartillaUsuario) :
                new ObjectParameter("idCartillaUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PronosticosCartillaUsuario_Result>("SP_PronosticosCartillaUsuario", idCartillaUsuarioParameter);
        }
    
        public virtual int SP_PROC_CreaPronosticos(Nullable<int> idCartillaUsuario)
        {
            var idCartillaUsuarioParameter = idCartillaUsuario.HasValue ?
                new ObjectParameter("idCartillaUsuario", idCartillaUsuario) :
                new ObjectParameter("idCartillaUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PROC_CreaPronosticos", idCartillaUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_RevisaCartilla_Result> SP_RevisaCartilla(Nullable<int> idCartilla, Nullable<int> idUsuario)
        {
            var idCartillaParameter = idCartilla.HasValue ?
                new ObjectParameter("idCartilla", idCartilla) :
                new ObjectParameter("idCartilla", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RevisaCartilla_Result>("SP_RevisaCartilla", idCartillaParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_PosicionesCartilla_Result> SP_PosicionesCartilla(Nullable<int> idCartilla, Nullable<int> idUsuario, Nullable<int> cuanto)
        {
            var idCartillaParameter = idCartilla.HasValue ?
                new ObjectParameter("idCartilla", idCartilla) :
                new ObjectParameter("idCartilla", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var cuantoParameter = cuanto.HasValue ?
                new ObjectParameter("cuanto", cuanto) :
                new ObjectParameter("cuanto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PosicionesCartilla_Result>("SP_PosicionesCartilla", idCartillaParameter, idUsuarioParameter, cuantoParameter);
        }
    
        public virtual ObjectResult<SP_AvancesFaseCartilla_Result> SP_AvancesFaseCartilla(Nullable<int> idCartillaUsuario)
        {
            var idCartillaUsuarioParameter = idCartillaUsuario.HasValue ?
                new ObjectParameter("IdCartillaUsuario", idCartillaUsuario) :
                new ObjectParameter("IdCartillaUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_AvancesFaseCartilla_Result>("SP_AvancesFaseCartilla", idCartillaUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_PosicionesCartillaBando_Result> SP_PosicionesCartillaBando(Nullable<int> idCartilla, Nullable<int> idUsuario, Nullable<int> idBando)
        {
            var idCartillaParameter = idCartilla.HasValue ?
                new ObjectParameter("idCartilla", idCartilla) :
                new ObjectParameter("idCartilla", typeof(int));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idBandoParameter = idBando.HasValue ?
                new ObjectParameter("idBando", idBando) :
                new ObjectParameter("idBando", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PosicionesCartillaBando_Result>("SP_PosicionesCartillaBando", idCartillaParameter, idUsuarioParameter, idBandoParameter);
        }
    
        public virtual ObjectResult<SP_BandosUsuario_Result> SP_BandosUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BandosUsuario_Result>("SP_BandosUsuario", idUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_PosicionesGeneralesBando_Result> SP_PosicionesGeneralesBando(Nullable<int> idUsuario, Nullable<int> cuanto, Nullable<int> idBando)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var cuantoParameter = cuanto.HasValue ?
                new ObjectParameter("cuanto", cuanto) :
                new ObjectParameter("cuanto", typeof(int));
    
            var idBandoParameter = idBando.HasValue ?
                new ObjectParameter("idBando", idBando) :
                new ObjectParameter("idBando", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PosicionesGeneralesBando_Result>("SP_PosicionesGeneralesBando", idUsuarioParameter, cuantoParameter, idBandoParameter);
        }
    
        public virtual ObjectResult<SP_PosicionesGenerales_Result> SP_PosicionesGenerales(Nullable<int> idUsuario, Nullable<int> cuanto)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var cuantoParameter = cuanto.HasValue ?
                new ObjectParameter("cuanto", cuanto) :
                new ObjectParameter("cuanto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PosicionesGenerales_Result>("SP_PosicionesGenerales", idUsuarioParameter, cuantoParameter);
        }
    
        public virtual ObjectResult<SP_PosicionesBandos_Result> SP_PosicionesBandos(Nullable<int> cuanto)
        {
            var cuantoParameter = cuanto.HasValue ?
                new ObjectParameter("cuanto", cuanto) :
                new ObjectParameter("cuanto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PosicionesBandos_Result>("SP_PosicionesBandos", cuantoParameter);
        }
    }
}
