//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USR_usuarios()
        {
            this.Cartillas = new HashSet<Cartillas>();
            this.CartillasUsuario = new HashSet<CartillasUsuario>();
            this.Pronosticos = new HashSet<Pronosticos>();
            this.UsuariosBandos = new HashSet<UsuariosBandos>();
            this.Bandos = new HashSet<Bandos>();
        }
    
        public int id { get; set; }
        public int idPersona { get; set; }
        public string nombreUsuario { get; set; }
        public string clave { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaModificacionPWD { get; set; }
        public Nullable<System.DateTime> fechaValidezPWD { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> debeCambiarClave { get; set; }
        public Nullable<int> ranking { get; set; }
        public Nullable<int> puntos { get; set; }
        public Nullable<int> posicion { get; set; }
        public Nullable<int> puntosNuevos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cartillas> Cartillas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartillasUsuario> CartillasUsuario { get; set; }
        public virtual MIS_Personas MIS_Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pronosticos> Pronosticos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosBandos> UsuariosBandos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bandos> Bandos { get; set; }
        public virtual Rankings Rankings { get; set; }
    }
}
