//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosBandos
    {
        public int id { get; set; }
        public int idBando { get; set; }
        public int idUsuario { get; set; }
        public bool estaAceptado { get; set; }
    
        public virtual Bandos Bandos { get; set; }
        public virtual USR_usuarios USR_usuarios { get; set; }
    }
}
